name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test EntityFramework.ServiceBus.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
